title: Migrate Windows & SQL workloads to Azure
description: This lab teaches you how to prepare for and securely migrate Windows Server and SQL Server workloads to Azure.
theme: just-the-docs

# url: https://microsoft.github.io/TechExcel-Securely-migrate-Windows-Server-and-SQL-Server-workloads-to-Azure//

aux_links:
  "TechExcel: Securely migrate Windows Server and SQL Server workloads to Azure": 
    - "https://github.com/vraposo/TechExcel-Securely-migrate-Windows-Server-and-SQL-Server-workloads-to-Azure"
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note 
    color: purple
  warning:
    title: Warning
    color: red
